quarkus:
  application:
    name: fastfood-order-service
  mongodb:
    connection-string: mongodb://localhost:27017
    #connection-string: mongodb://host.docker.internal:27017
    database: fastfoodDB